(function setupClimateConfig(global) {
  global.CCEClimateConfig = {
    versao: "2026.05.27-01",

    weatherApi: {
      enabled: true,
      workerUrl:
        "https://pcm-eletrovia-api.weslley-santos.workers.dev/api/clima/forecast",
      forecastDays: 16,
      mode: "district",
      cacheMinutes: 60,
      timezone: "America/Fortaleza",
      visaoPadrao: "mensal",
      periodosPadrao: ["manha", "tarde"],
      origensDataPadrao: ["Data replanejada", "Data planejada", "Vencimento"],
    },

    distritos: [
      {
        codigo: "SLZ",
        nome: "São Luís / TFPM",
        ga: "GAL 1",
        kmInicial: 0,
        kmFinal: 0,
        cidadeReferencia: "São Luís",
        uf: "MA",
        latitude: null,
        longitude: null,
        centrosTrabalho: [],
        observacao: "TFPM 1 e TFPM 2 tratados como KM 0.",
      },
      {
        codigo: "BAC",
        nome: "Bacabeira",
        ga: "GAL 1",
        kmInicial: 0,
        kmFinal: 81.97,
        cidadeReferencia: "Bacabeira",
        uf: "MA",
        latitude: null,
        longitude: null,
        centrosTrabalho: [],
      },
      {
        codigo: "VTM",
        nome: "Vitória do Mearim",
        ga: "GAL 2",
        kmInicial: 81.97,
        kmFinal: 165.364,
        cidadeReferencia: "Vitória do Mearim",
        uf: "MA",
        latitude: null,
        longitude: null,
        centrosTrabalho: [],
      },
      {
        codigo: "SIS",
        nome: "Santa Inês",
        ga: "GAL 2",
        kmInicial: 165.364,
        kmFinal: 257.796,
        cidadeReferencia: "Santa Inês",
        uf: "MA",
        latitude: null,
        longitude: null,
        centrosTrabalho: [],
      },
      {
        codigo: "AAL",
        nome: "Alto Alegre do Pindaré",
        ga: "GAL 2",
        kmInicial: 257.796,
        kmFinal: 335.21,
        cidadeReferencia: "Alto Alegre do Pindaré",
        uf: "MA",
        latitude: null,
        longitude: null,
        centrosTrabalho: [],
      },
      {
        codigo: "NVA",
        nome: "Nova Vida",
        ga: "GAL 2",
        kmInicial: 335.21,
        kmFinal: 446.111,
        cidadeReferencia: "Nova Vida",
        uf: "MA",
        latitude: null,
        longitude: null,
        centrosTrabalho: [],
      },
      {
        codigo: "ACD",
        nome: "Açailândia",
        ga: "GAL 3",
        kmInicial: 446.111,
        kmFinal: 609.71,
        cidadeReferencia: "Açailândia",
        uf: "MA",
        latitude: null,
        longitude: null,
        centrosTrabalho: [],
      },
      {
        codigo: "SPD",
        nome: "São Pedro",
        ga: "GAL 3",
        kmInicial: 609.71,
        kmFinal: 697.354,
        cidadeReferencia: "São Pedro",
        uf: "MA",
        latitude: null,
        longitude: null,
        centrosTrabalho: [],
      },
      {
        codigo: "MBA",
        nome: "Marabá",
        ga: "GAL 3",
        kmInicial: 697.354,
        kmFinal: 792.28,
        cidadeReferencia: "Marabá",
        uf: "PA",
        latitude: null,
        longitude: null,
        centrosTrabalho: [],
      },
      {
        codigo: "PBA",
        nome: "Parauapebas",
        ga: "GAL 4",
        kmInicial: 792.28,
        kmFinal: 861.7,
        cidadeReferencia: "Parauapebas",
        uf: "PA",
        latitude: null,
        longitude: null,
        centrosTrabalho: [],
      },
      {
        codigo: "CJS",
        nome: "Carajás / Serra Sul",
        ga: "GAL 4",
        kmInicial: 861.7,
        kmFinal: 889.55,
        cidadeReferencia: "Carajás",
        uf: "PA",
        latitude: null,
        longitude: null,
        centrosTrabalho: [],
      },
      {
        codigo: "RFSP",
        nome: "Ramal Ferroviário Sul do Pará",
        ga: "GAL 4",
        kmInicial: null,
        kmFinal: null,
        cidadeReferencia: "RFSP",
        uf: "PA",
        latitude: null,
        longitude: null,
        centrosTrabalho: [],
        regraEspecial: true,
        observacao:
          "RFSP será tratado por regra especial. Não usar KM da imagem como referência principal.",
      },
    ],

    riscos: {
      favoravel: {
        label: "Favorável",
        nivel: 1,
      },
      atencao: {
        label: "Atenção",
        nivel: 2,
      },
      alto: {
        label: "Alto",
        nivel: 3,
      },
      critico: {
        label: "Crítico",
        nivel: 4,
      },
    },

    atividadesSensiveis: [
      {
        chave: "ESMERILHAMENTO",
        sensibilidade: "Alta",
      },
      {
        chave: "TRILHO",
        sensibilidade: "Alta",
      },
      {
        chave: "TLS",
        sensibilidade: "Alta",
      },
      {
        chave: "SUBSTITUICAO",
        sensibilidade: "Alta",
      },
      {
        chave: "SUBSTITUIÇÃO",
        sensibilidade: "Alta",
      },
      {
        chave: "ELETRICA",
        sensibilidade: "Alta",
      },
      {
        chave: "ELÉTRICA",
        sensibilidade: "Alta",
      },
      {
        chave: "INSPECAO",
        sensibilidade: "Média",
      },
      {
        chave: "INSPEÇÃO",
        sensibilidade: "Média",
      },
      {
        chave: "ROCO",
        sensibilidade: "Média",
      },
      {
        chave: "ROÇO",
        sensibilidade: "Média",
      },
    ],
  };
})(window);
