(function setupDiagnosticoConfig(global) {
  "use strict";

  const REPORT_SECTION_PRESETS = Object.freeze({
    executivo: Object.freeze({
      label: "Executivo",
      secoes: Object.freeze({
        diagSecaoCapa: true,
        diagSecaoResumoExecutivo: true,
        diagSecaoKpis: true,
        diagSecaoPrioridades: true,
        diagSecaoPlanejamento: false,
        diagSecaoCentros: true,
        diagSecaoPlanejadores: false,
        diagSecaoKm: false,
        diagSecaoPatios: true,
        diagSecaoTolerancias: false,
        diagSecaoVencimentos: true,
        diagSecaoClima: false,
        diagSecaoListaCritica: true,
        diagSecaoRecomendacoes: true,
      }),
      opcoes: Object.freeze({
        diagIncluirGraficos: true,
        diagIncluirTabelaOms: false,
        diagIncluirSomenteCriticas: true,
        diagIncluirDemandasSemKm: false,
        diagIncluirDetalhamentoCompleto: false,
      }),
      tituloPadrao: "Diagnóstico Executivo da Carteira",
      descricao:
        "Relatório sintético para leitura gerencial, com KPIs, prioridades, riscos, vencimentos e recomendações.",
    }),
    m1: Object.freeze({
      label: "Planejamento M+1",
      secoes: Object.freeze({
        diagSecaoCapa: true,
        diagSecaoResumoExecutivo: true,
        diagSecaoKpis: true,
        diagSecaoPrioridades: true,
        diagSecaoPlanejamento: true,
        diagSecaoCentros: true,
        diagSecaoPlanejadores: true,
        diagSecaoKm: true,
        diagSecaoPatios: true,
        diagSecaoTolerancias: true,
        diagSecaoVencimentos: true,
        diagSecaoClima: true,
        diagSecaoListaCritica: true,
        diagSecaoRecomendacoes: true,
      }),
      opcoes: Object.freeze({
        diagIncluirGraficos: true,
        diagIncluirTabelaOms: true,
        diagIncluirSomenteCriticas: false,
        diagIncluirDemandasSemKm: true,
        diagIncluirDetalhamentoCompleto: true,
      }),
      tituloPadrao: "Diagnóstico de Planejamento M+1",
      descricao:
        "Relatório completo para reunião de planejamento de curto prazo, com prioridades, datas, vencimentos, tolerâncias, centros, KM e clima.",
    }),
    planejador: Object.freeze({
      label: "Por Planejador de Curto",
      secoes: Object.freeze({
        diagSecaoCapa: true,
        diagSecaoResumoExecutivo: true,
        diagSecaoKpis: true,
        diagSecaoPrioridades: true,
        diagSecaoPlanejamento: true,
        diagSecaoCentros: false,
        diagSecaoPlanejadores: true,
        diagSecaoKm: false,
        diagSecaoPatios: true,
        diagSecaoTolerancias: true,
        diagSecaoVencimentos: true,
        diagSecaoClima: false,
        diagSecaoListaCritica: true,
        diagSecaoRecomendacoes: true,
      }),
      opcoes: Object.freeze({
        diagIncluirGraficos: true,
        diagIncluirTabelaOms: true,
        diagIncluirSomenteCriticas: false,
        diagIncluirDemandasSemKm: false,
        diagIncluirDetalhamentoCompleto: false,
      }),
      tituloPadrao: "Diagnóstico por Planejador de Curto",
      descricao:
        "Relatório focado em carga, prioridades, aderência, vencimentos e pendências por planejador.",
    }),
    centro: Object.freeze({
      label: "Por Centro de Trabalho",
      secoes: Object.freeze({
        diagSecaoCapa: true,
        diagSecaoResumoExecutivo: true,
        diagSecaoKpis: true,
        diagSecaoPrioridades: true,
        diagSecaoPlanejamento: true,
        diagSecaoCentros: true,
        diagSecaoPlanejadores: false,
        diagSecaoKm: true,
        diagSecaoPatios: true,
        diagSecaoTolerancias: true,
        diagSecaoVencimentos: true,
        diagSecaoClima: true,
        diagSecaoListaCritica: true,
        diagSecaoRecomendacoes: true,
      }),
      opcoes: Object.freeze({
        diagIncluirGraficos: true,
        diagIncluirTabelaOms: true,
        diagIncluirSomenteCriticas: false,
        diagIncluirDemandasSemKm: true,
        diagIncluirDetalhamentoCompleto: false,
      }),
      tituloPadrao: "Diagnóstico por Centro de Trabalho",
      descricao:
        "Relatório focado em centro, prioridades, local de instalação, KM, vencimentos, tolerâncias e riscos de execução.",
    }),
    supervisao: Object.freeze({
      label: "Por Supervisão/Gerência",
      secoes: Object.freeze({
        diagSecaoCapa: true,
        diagSecaoResumoExecutivo: true,
        diagSecaoKpis: true,
        diagSecaoPrioridades: true,
        diagSecaoPlanejamento: true,
        diagSecaoCentros: true,
        diagSecaoPlanejadores: true,
        diagSecaoKm: true,
        diagSecaoPatios: true,
        diagSecaoTolerancias: true,
        diagSecaoVencimentos: true,
        diagSecaoClima: true,
        diagSecaoListaCritica: true,
        diagSecaoRecomendacoes: true,
      }),
      opcoes: Object.freeze({
        diagIncluirGraficos: true,
        diagIncluirTabelaOms: true,
        diagIncluirSomenteCriticas: false,
        diagIncluirDemandasSemKm: true,
        diagIncluirDetalhamentoCompleto: true,
      }),
      tituloPadrao: "Diagnóstico por Supervisão/Gerência",
      descricao:
        "Relatório para gestão da carteira por supervisão ou gerência, com foco em prioridades, distribuição, risco, centros e vencimentos.",
    }),
    clima: Object.freeze({
      label: "Risco Climático",
      secoes: Object.freeze({
        diagSecaoCapa: true,
        diagSecaoResumoExecutivo: true,
        diagSecaoKpis: true,
        diagSecaoPrioridades: true,
        diagSecaoPlanejamento: true,
        diagSecaoCentros: true,
        diagSecaoPlanejadores: false,
        diagSecaoKm: true,
        diagSecaoPatios: true,
        diagSecaoTolerancias: false,
        diagSecaoVencimentos: true,
        diagSecaoClima: true,
        diagSecaoListaCritica: true,
        diagSecaoRecomendacoes: true,
      }),
      opcoes: Object.freeze({
        diagIncluirGraficos: true,
        diagIncluirTabelaOms: true,
        diagIncluirSomenteCriticas: false,
        diagIncluirDemandasSemKm: false,
        diagIncluirDetalhamentoCompleto: false,
      }),
      tituloPadrao: "Diagnóstico de Risco Climático",
      descricao:
        "Relatório focado em atividades sensíveis ao clima, prioridades, datas planejadas, centros críticos e recomendações de janela operacional.",
    }),
    completo: Object.freeze({
      label: "Completo",
      secoes: Object.freeze({
        diagSecaoCapa: true,
        diagSecaoResumoExecutivo: true,
        diagSecaoKpis: true,
        diagSecaoPrioridades: true,
        diagSecaoPlanejamento: true,
        diagSecaoCentros: true,
        diagSecaoPlanejadores: true,
        diagSecaoKm: true,
        diagSecaoPatios: true,
        diagSecaoTolerancias: true,
        diagSecaoVencimentos: true,
        diagSecaoClima: true,
        diagSecaoListaCritica: true,
        diagSecaoRecomendacoes: true,
      }),
      opcoes: Object.freeze({
        diagIncluirGraficos: true,
        diagIncluirTabelaOms: true,
        diagIncluirSomenteCriticas: false,
        diagIncluirDemandasSemKm: true,
        diagIncluirDetalhamentoCompleto: true,
      }),
      tituloPadrao: "Diagnóstico Completo da Carteira",
      descricao:
        "Relatório completo com todas as seções técnicas disponíveis, incluindo prioridades operacionais.",
    }),
  });

  const diagnosticoConfig = Object.freeze({
    reportName: "Diagnóstico da Carteira",
    centralName: "Central de Controle PCM Eletrovia",
    palette: Object.freeze({
      primary: "#105c44",
      primarySoft: "#edf5f1",
      accent: "#c97a00",
      danger: "#b42318",
      text: "#17342a",
      muted: "#5d7068",
      border: "rgba(16, 92, 68, 0.14)",
      surface: "#ffffff",
      background: "#f4f8f6",
    }),
    reportTypes: Object.freeze([
      { id: "executivo", label: "Executivo" },
      { id: "m1", label: "Planejamento M+1" },
      { id: "planejador", label: "Por Planejador de Curto" },
      { id: "centro", label: "Por Centro de Trabalho" },
      { id: "supervisao", label: "Por Supervisão/Gerência" },
      { id: "clima", label: "Risco Climático" },
      { id: "completo", label: "Completo" },
    ]),
    selectableSections: Object.freeze([
      { id: "diagSecaoCapa", label: "Capa executiva" },
      { id: "diagSecaoResumoExecutivo", label: "Resumo executivo" },
      { id: "diagSecaoKpis", label: "KPIs da carteira" },
      { id: "diagSecaoPrioridades", label: "Prioridades operacionais" },
      { id: "diagSecaoPlanejamento", label: "Planejamento por data" },
      { id: "diagSecaoCentros", label: "Análise por centro de trabalho" },
      { id: "diagSecaoPlanejadores", label: "Análise por planejador de curto" },
      { id: "diagSecaoKm", label: "Análise por KM e trecho" },
      { id: "diagSecaoPatios", label: "Análise por pátio" },
      { id: "diagSecaoTolerancias", label: "Tolerâncias e janelas de execução" },
      { id: "diagSecaoVencimentos", label: "Vencimentos e atrasos" },
      { id: "diagSecaoClima", label: "Risco climático" },
      { id: "diagSecaoListaCritica", label: "Lista crítica de acompanhamento" },
      { id: "diagSecaoRecomendacoes", label: "Recomendações técnicas" },
    ]),
    REPORT_SECTION_PRESETS,
  });

  global.CCEDiagnosticoConfig = Object.freeze({
    ...(global.CCEDiagnosticoConfig || {}),
    ...diagnosticoConfig,
    REPORT_SECTION_PRESETS,
  });
})(window);
